# Generated by Django 3.1.3 on 2020-11-20 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('phone_no', models.CharField(max_length=11, null=True)),
                ('whatsapp_no', models.CharField(max_length=11, null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('intagram_link', models.URLField(null=True)),
                ('twitter_link', models.URLField(null=True)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barbers.profile')),
            ],
        ),
    ]
