# Generated by Django 3.1.3 on 2020-11-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_auto_20201120_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
