# Generated by Django 3.1.3 on 2020-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_auto_20201120_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
