# Generated by Django 3.1.3 on 2020-11-20 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_profile_home_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
