# Generated by Django 3.1.3 on 2020-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0008_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(default='haircream', unique=True),
        ),
    ]
